### ISSUE TITLE
map_slow_requests_to_buckets.sh errors when bucket name contains "-"

### ISSUE THREAD

**Issue by haklein** [linuxkidd/ceph-log-parsers#1]
When using crush bucket names containing a "-" character, like "storage-node" instead of the default "host" bucket, the `declare` on line 72 will fail:
~~~
./map_slow_requests_to_buckets.sh: line 72: declare: `storage-node=mystoragenode01': not a valid identifier
~~~

**Comment by haklein** [comment]
q'n'd hack: 
~~~
30	thirdcol=$(echo $line | awk '{print $3}' | tr -d -c "[:alnum:]_")
~~~

**Comment by linuxkidd** [comment]
Hey @haklein , I had come across this issue too and attempted a similar q'n'd hack.. but.. found that it prevented future grep matches.  Have you tested your tr option to ensure it still reports anything other than 0 counts on the output?

**Comment by linuxkidd** [comment]
I think at this point, this script is deprecated in favor of the ceph-log-parser.awk scripts.  I'll remove the 'map_slow_requests_to_buckets.sh' script (if not done already).  Closing this issue.
